# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88988745a2cae36096fbda65bf73ca11029e504291ca633d3adcf01a658e3b6b716b60076fa9d8b565abb454bb01dc5c6e8c010e2490067df9ed87fcf710d41c

test:
  secret_key_base: aca37c3cfb8bed76a2a46c501d0f0f2356bb2201e60d82cd2efed20deb8570971f9779e04a9149a97b3025381d60f20e44b01e0e3a7fc2954a86f98cb4588732

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
